# coding: utf-8

"""
    ObsLabs API

    # Authentication  ObsLabs uses basic auth to authenticate the API. You can create API keys in the account settings. Use your API key as the basic auth password. The username should be left blank (notice the colon sign before api-key that must be included). All requests must be made over https.  Example usage: ```bash curl -u :<YOUR API KEY> https://api.obslabs.io/v1/users/me ```  # Errors  The API returns a structured error response in case of failure. Below is the format of the error response object:  ```json {   \"error\": {     \"status\": 400,     \"code\": \"VALIDATION\",     \"message\": \"Validation errors occurred.\",     \"details\": [       {         \"field\": \"email\",         \"issue\": \"The email address is not in a valid format.\"       },       {         \"field\": \"password\",         \"issue\": \"The password must be at least 8 characters long.\"       }     ]   } } 

    The version of the OpenAPI document: 1.0
    Contact: contact@obslabs.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from obslabs_client.api.invitations_api import InvitationsApi


class TestInvitationsApi(unittest.TestCase):
    """InvitationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvitationsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_accept_invitation(self) -> None:
        """Test case for v1_accept_invitation

        Accept Invitation
        """
        pass

    def test_v1_get_invitation(self) -> None:
        """Test case for v1_get_invitation

        Get Invitation
        """
        pass

    def test_v1_list_invitations(self) -> None:
        """Test case for v1_list_invitations

        List Invitations
        """
        pass

    def test_v1_resend_invitation(self) -> None:
        """Test case for v1_resend_invitation

        Resend Invitation
        """
        pass

    def test_v1_revoke_invitation(self) -> None:
        """Test case for v1_revoke_invitation

        Revoke Invitation
        """
        pass

    def test_v1_send_invitation(self) -> None:
        """Test case for v1_send_invitation

        Send Invitation
        """
        pass


if __name__ == '__main__':
    unittest.main()
